### ISSUE TITLE
Improve comment alignment

### ISSUE THREAD

**Issue by patxoca** [reidrac/z80count#12]
Currently the comments added by `z80count` are padded using a fixed amount of tabs (2 by default, overridable with `-t`). It ignores the actual length of the line and comments may appear misaligned.

**Comment by reidrac** [comment]
I didn't find a good solution to this.

I guess you can set a column to pad to and then use spaces, but most of the ASM files I have use tabs instead.

**Comment by patxoca** [comment]
It's what I've done. The user specifies a column and can choose to use tabs or spaces. It is smart enough to account correctly (I hope) for tabs.

The PR has a lot of changes, some opinionated. Let me know what you think and if it works OK with your particular use case.

**Comment by reidrac** [comment]
I'll look at it :+1: 

I would like you to branch from master here before submitting a PR so its history is clean. The way you have been doing it until now means I'll have to squash the changes before merging.

You can track this repo's master in your fork.

**Comment by reidrac** [comment]
> It's what I've done. The user specifies a column and can choose to use tabs or spaces. It is smart enough to account correctly (I hope) for tabs.
> 
> The PR has a lot of changes, some opinionated. Let me know what you think and if it works OK with your particular use case.

I reviewed the code and I like it! I made some comments mostly about style, I hope it's OK!

**Comment by patxoca** [comment]
Sorry for the annoyance. I'm not very proficient at git, mostly a subversion user. I'll investigate.

For this PR I've created a new branch (https://github.com/patxoca/z80count/tree/align-comments) in my repo from my master that mirrors (tracks?) yours. I assume that is not the right way.

**Comment by reidrac** [comment]
When tracking this master on your master don't merge, rebase instead. You can also create a branch from this master instead. Is not a big deal but I'll have to squash your commits and we'll lose any intermediate commit you made that could be useful to have.

The end result will be the same in one single commit. Don't worry too much about it unless you want to investigate a bit on how to use git and GitHub.

This is a good "how to": https://stackoverflow.com/questions/7244321/how-do-i-update-a-github-forked-repository#7244456

The key here is "rebase" instead of "merge", and never commit changes to your master and use a feature branch instead. You may not even use your local master at all and branch from here.

**Comment by reidrac** [comment]
Done in #13

**Comment by patxoca** [comment]
Thanks for the pointers, I'll take a look. I need to get used to git's practices.

Regarding my question about using spaces by default for comment padding, currently It **is** the default. If you prefer TABs, please, fix it in your repo and I'll try to rebase mine and see if all works.

**Comment by reidrac** [comment]
Currently the defaults aren't clear. I'll see how I can change that to make it clearer.
