### ISSUE TITLE
Provide a config file

### ISSUE THREAD

**Issue by patxoca** [reidrac/z80count#16]
It would be nice to have a config file to override the defaults.

My proposal (sort of):

- no external dependencies. There are already libraries out there for this task but probably they are bigger than `z80count` itself. I would like to keep it simple and small.

- use an INI like config file (`configparser`)

- use the nearest config file (from the current directory, parent directory ... until we reach the root of the filesystem). That way we can have per project configurations. If no config files is found just use the defaults.

- the content of that file overrides the defaults used in the command line parser which ultimately gives the actual values.

Not sure if this is a bit overkill but I think it would be useful to have per project options that make `z80count` invocation simpler.

**Comment by reidrac** [comment]
> It would be nice to have a config file to override the defaults.
> 
> My proposal (sort of):
> 
>     * no external dependencies. There are already libraries out there for this task but probably they are bigger than `z80count` itself. I would like to keep it simple and small.

OK, let's use functionality that comes with Python.

>     * use an INI like config file (`configparser`)

Sounds good to me.

>     * use the nearest config file (from the current directory, parent directory ... until we reach the root of the filesystem). That way we can have per project configurations. If no config files is found just use the defaults.

I don't like this; it is expensive if there's no local configuration, and it is a bit too much for this use case.

Having a configuration file with defaults could be useful but I don't think it is that necessary to support conf files per project (do they change that much? we don't have that many flags here!).

If you **really** need this, I would suggest instead:

 - Check current directory (other tools do this, e.g. ctags)
 - Check for conf in `XDG_CONFIG_HOME` if defined, otherwise in `HOME`
 - Support `Z80COUNT_RC` env variable to provide the location of the configuration file

>     * the content of that file overrides the defaults used in the command line parser which ultimately gives the actual values.

It should be:

 - Configuration file defaults (in case it doesn't exist) are the defaults
 - The CLI can override the defaults
 
> Not sure if this is a bit overkill but I think it would be useful to have per project options that make `z80count` invocation simpler.

It can be useful to have a configuration file, but I don't really see the need of maintaining per project configutaion.

This is an enhancement, but IMHO is more likely people using this often will have a keyboard command to execute the tool with the appropriate flags (I know I do). There aren't that many things to configure anyway, this may mean one or two flags.

**Comment by patxoca** [comment]
The use case for per project configuration is for people collaborating and having different preferences. My global config reflects my preferences (spaces over tabs) and the project specific config the agreed ones.

I like the idea of `Z80COUNT_RC`, that way the _project_ can setup the variable and use different defaults.

When I started coding I felt like it may be too much for such a small tool. Don't feel compelled to accept  the PR.

**Comment by reidrac** [comment]
Done in #17.
